### ISSUE TITLE
BLAS pinned to MKL in x64 is problematic in macOS rosetta environments

### ISSUE THREAD

**Issue by sdvillal** [conda-forge/pytorch-cpu-feedstock#101]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Pytorch cannot be installed in a macOS rosetta environment emulating x64 because our recipe pins BLAS to MKL (for example, **[here](https://github.com/conda-forge/pytorch-cpu-feedstock/blob/93333de760d702aee276dcafeedc890458a00417/recipe/meta.yaml#L93-L94))**. In turn, MKL refuses to run in a rosetta environment after some runtime checks.

To reproduce, in an M1 mac machine and an x86_64 conda installation, run:
```sh
conda create -n pytorch-test -c conda-forge pytorch
```

To fix this, we would need to build against other BLAS option and allow to use it in rosetta environments. But I do not know if there is a conda selector or other mechanism we could use to detect that is the case.

As a workaround we can pin MKL to version <2022, which does not seem to include the runtime check. I do not know if this can lead to problems further down the line.

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by hmaarrfk** [comment]
Does pytorch support other blas implementions today?

**Comment by sdvillal** [comment]
Hi Mark, thanks for the quick reaction. I am not an expert, but it seems that we are already building pytorch against openblas in non-intel architectures. So my plan was to open a PR had I found the correct selector.

Do you know better?

**Comment by hmaarrfk** [comment]
Don't we like to compile with netlib? I remember there being some performance concerns.

**Comment by isuruf** [comment]
@hmaarrfk, yes, but in the case of pytorch-cpu, MKL provides BLAS/LAPACK and FFT functionality whereas OpenBLAS provides only BLAS/LAPACK and not using MKL leads to performance issues.

**Comment by hmaarrfk** [comment]
So when we build with netlib, we would not get the FFT speedups even when mkl is used.

Is this correct?

**Comment by isuruf** [comment]
Yes

**Comment by ngam** [comment]
Weirdly enough, both osx-64 and osx-arm64 from the pytorch channel use `blas * mkl`:

<h4 class="modal-title" id="myModalLabel" style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0.2rem 0px 0.5rem; padding: 0px; color: rgb(34, 34, 34); font-family: &quot;Museo Sans Rounded&quot;, Lato, &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif; font-weight: 400; line-height: 1.4; text-rendering: optimizeLegibility; font-size: 1.4375rem; caret-color: rgb(34, 34, 34);">osx-arm64/pytorch-1.11.0.arm64-py3.8_0.tar.bz2</h4><p class="subheader" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0.2rem 0px 0.5rem; padding: 0px; font-family: &quot;Museo Sans Rounded&quot;, Lato, &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif; text-rendering: optimizeLegibility; line-height: 1.4; color: rgb(111, 111, 111);">None</p><div style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px; padding: 0px; caret-color: rgb(34, 34, 34); color: rgb(34, 34, 34); font-family: &quot;Museo Sans Rounded&quot;, Lato, &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif;">

Uploaded | Tue Mar 8 17:37:22 2022
-- | --
md5 checksum | bbb8388ed99dc92a4c42b15e8676ecb5
arch | arm64
build | py3.8_0
constrains | cpuonly
depends | blas * mkl, libuv >=1.40.0,<2.0a0, mkl >=2018, python >=3.8,<3.9.0a0, typing_extensions
has_prefix | True
license | BSD 3-Clause
license_family | BSD
machine | arm64
operatingsystem | darwin
platform | osx
subdir | osx-arm64
target-triplet | arm64-any-darwin
timestamp | 1646760808089

</div>

<h4 class="modal-title" id="myModalLabel" style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0.2rem 0px 0.5rem; padding: 0px; color: rgb(34, 34, 34); font-family: &quot;Museo Sans Rounded&quot;, Lato, &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif; font-weight: 400; line-height: 1.4; text-rendering: optimizeLegibility; font-size: 1.4375rem; caret-color: rgb(34, 34, 34);">osx-64/pytorch-1.11.0-py3.8_0.tar.bz2</h4><p class="subheader" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0.2rem 0px 0.5rem; padding: 0px; font-family: &quot;Museo Sans Rounded&quot;, Lato, &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif; text-rendering: optimizeLegibility; line-height: 1.4; color: rgb(111, 111, 111);">None</p><div style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px; padding: 0px; caret-color: rgb(34, 34, 34); color: rgb(34, 34, 34); font-family: &quot;Museo Sans Rounded&quot;, Lato, &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif;">

Uploaded | Tue Mar 8 17:29:22 2022
-- | --
md5 checksum | b8af1010dc91d3137a74e17f0f31d092
arch | x86_64
build | py3.8_0
constrains | cpuonly
depends | blas * mkl, libuv >=1.40.0,<2.0a0, mkl >=2018, python >=3.8,<3.9.0a0, typing_extensions
has_prefix | True
license | BSD 3-Clause
license_family | BSD
machine | x86_64
operatingsystem | darwin
platform | osx
subdir | osx-64
target-triplet | x86_64-any-darwin
timestamp | 1646760218080

</div>

**Comment by sdvillal** [comment]
Right now our problem is with rosetta environments + MKL>2022. 

If the difference between MKL and OpenBLAS is performance, we could enable building pytorch against a generic BLAS in x64. This would give us the chance to escape the MKL trap. I do not know if it is feasible and how much of an effort this can be, both human and computational. For us it is alright at the moment not to start it, as we can still work with recent pytorch  and slightly outdated MKL versions. We are also happy to assist if expanding the build matrix would be an option.

As a side note, this is likely a niche problem. We need to use rosetta because we lack the manpower to drive porting several bioinformatics packages without an osx-arm64 version. But this is a problem only with the newer laptops provided by our company, which we use to develop. We do run our computations somewhere else. Therefore, we do not mind that things are not as fast as they can be as long as we can comfortably hack in these local environments.

**Comment by ngam** [comment]
> Right now our problem is with rosetta environments + MKL>2022.

Ah!!

> 
> If the difference between MKL and OpenBLAS is performance, we could enable building pytorch against a generic BLAS in x64. This would give us the chance to escape the MKL trap. I do not know if it is feasible and how much of an effort this can be, both human and computational. For us it is alright at the moment not to start it, as we can still work with recent pytorch and slightly outdated MKL versions. We are also happy to assist if expanding the build matrix would be an option.
> 


We could aways make installing another BLAS an option, though it will require some editing in this recipe here. One would need to set it up correctly meta.yaml and the other config yamls, and relax the hard condition on the BLAS in build.sh. If you're interested in a PR, this was my attempt at trying implementing the accelerate backend, though it was not worth it after all: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/88 (more discussions here: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/83)

> As a side note, this is likely a niche problem. We need to use rosetta because we lack the manpower to drive porting several bioinformatics packages without an osx-arm64 version. But this is a problem only with the newer laptops provided by our company, which we use to develop. We do run our computations somewhere else. Therefore, we do not mind that things are not as fast as they can be as long as we can comfortably hack in these local environments.

To clarify though, I assume you're running your computations on a linux-64 machine, right? I am not sure, but wouldn't make sense to do the developing on a linux-64 machine then (or using things like multipass, docker, etc.)?

**Comment by hmaarrfk** [comment]
@sdvillal you are right that this is a niche problem. You might find it much faster to release your own packages without MKL before waiting for concensus. In sure you likely already have a solution.

However, i would accept a PR if you can help ensure that MKL stays priorifized if no special options are specifies.

**Comment by sdvillal** [comment]
We also feel that only if the workaround stops working, or more people report being bitten by this problem, it is worth to try adding a variant for the package.

Thanks everyone for the input.
