### ISSUE TITLE
CHECKLIST FOR v1.12

### ISSUE THREAD

**Issue by ngam** [conda-forge/pytorch-cpu-feedstock#107]
### Comment:

TODO:
- [x] add `__cuda` and `_track_features` as per #105 
- [ ] add `mps` variant as per #106 
- [x] #114 

Comments:
- `__cuda` is ready, just needs to be added in the next build.
- `mps` support is ready. I recommend a separate branch, a la dev branch, because for `mps` to work without hassle, we could easily just rely on the latest macos-12 image instead figuring out a matrix --- unclear to me how to select two different osx azure files in ci_support...

Edit: re-opening again to include 114

**Comment by ngam** [comment]
Closing as all items have been address.

**Comment by hmaarrfk** [comment]
i'm still confused as to how the MPS variant has been addressed.

**Comment by ngam** [comment]
> i'm still confused as to how the MPS variant has been addressed.
-
I tested it (on the M1 Mac)! I downloaded the build_artifacts from Azure from one of the PRs. It works beautifully, so once we have the 1.12 release, we will just build it.

The only remaining problem there is the choice between:

(Remember: We have to set a strict run condition for macos 12.3 --- as I explained elsewhere, macos 12.4 was just released a few weeks ago, and there is not even sdk 12.4 yet, so it is really current)

1. Make a dev/mps branch and just carefully target PRs to that
2. Figure out the complicated CI/conda-smithy/macos-SDKs matrix stuff.

I concluded that I really am not up to the challenge of option 2 at this point. So I was going to ask you to make a branch, call it "mps" or something, and then I can make a PR for only the MPS variant to that branch. And I can maintain that branch going forward by submitting PRs to keep pace with whatever happens on the main branch (since you don't have a mac to test it, I think, right?)

Does this make sense?

**Comment by hmaarrfk** [comment]
I understand the technical tradeoffs, but I don't understand why the checklist was closed :/

**Comment by hmaarrfk** [comment]
Don't you want to keep a checklist open until we finish 1.12?

**Comment by ngam** [comment]
Oh, because the items were checked off, I thought we'd close it, but let's reopen it if you want!

**Comment by ngam** [comment]
We can add more issues as they come too. Btw, I know there are cuda failures that I saw last time I was building the mps variants, so I will try to see these for you and print out the errors for you to investigate

**Comment by ngam** [comment]
Let's add the MKLDNN issue to this list to investigate? It's in in fact not activated:  `USE_MKLDNN=OFF`

```
~$ python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch

>>> 
>>> torch.__config__.show()
'PyTorch built with:\n  - GCC 10.3\n  - C++ Version: 201402\n  - Intel(R) oneAPI Math Kernel Library Version 2022.1-Product Build 20220311 for Intel(R) 64 architecture applications\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1654951030282/_build_env/bin/x86_64-conda-linux-gnu-c++, CXX_FLAGS=-std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1654951030282/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1654951030282/work=/usr/local/src/conda/pytorch-1.11.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1654951030282/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix -Wno-deprecated-declarations -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'
>>> 

```

**Comment by ngam** [comment]
(Note: I never really managed to get `USE_MPS=1` to work by setting the flag, it only worked for me when macos was 12.3+, so ... this may be a similar issue? Our flags in build.sh are not getting through sometimes?)
