### ISSUE TITLE
what went wrong with osx builds?

### ISSUE THREAD

**Issue by ngam** [conda-forge/pytorch-cpu-feedstock#132]
### Comment:

#131
#127

Most of these changes don't seem to have a real impact. I am trying to figure out if there was a failure somewhere so that we can better track it in the future. Everything ran smoothly for me when I tested locally... 

cc @hmaarrfk

**Comment by hmaarrfk** [comment]
>  - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }} # [osx] would have gone to default anyway


I'm convinced that this isn't the case of the arm64 builds. These packages just don't depend on anything and just hope that the minimum for conda is 11.0
