### ISSUE TITLE
Add ARM + CUDA packages

### ISSUE THREAD

**Issue by bdice** [conda-forge/pytorch-cpu-feedstock#149]
Builds of the package for aarch64 (ARM) with CUDA support are missing and would be nice to have.

This would be helpful to RAPIDS cuDF, which uses PyTorch in its test suite for checking GPU interoperability. Currently cuDF is using an older pinning of `pytorch/pytorch` < 1.12.0 (rather than the conda-forge package) to get ARM + CUDA support. Newer versions on the `pytorch` channel are built with `nvidia/cuda-toolkit` instead of `conda-forge/cudatoolkit`, which leads to linker incompatibilities with libcupti.

cc: @jakirkham

**Comment by jakirkham** [comment]
This was added to the arch migration indirectly by PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/504 ) and then directly in PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2699 ). The latter being done after setting up the CUDA arch migrator ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2527 )

The arch migration for PyTorch is started in PR ( https://github.com/conda-forge/pytorch-cpu-feedstock/pull/119 ). Though that handles the CPU case. The CUDA case is handled by a follow on CUDA arch migrator. Though both could be applied in a single PR (if preferred).

That all being said, the main challenge will be working through the build issues seen currently to get that to work.

**Comment by njzjz** [comment]
When I tried it, I found the current `build.sh` cannot find the target CUDA correctly for cross-building.

```
  -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR) (found version "11.8")^M
  CMake Warning at cmake/public/cuda.cmake:31 (message):^M
    Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2^M
    or a Caffe2 dependent library, the next warning / error will give you more^M
    info.^M
  Call Stack (most recent call first):^M
    cmake/Dependencies.cmake:44 (include)^M
    CMakeLists.txt:722 (include)^M
```

**Comment by jakirkham** [comment]
We probably need this logic: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/203#discussion_r1387308111

**Comment by jakirkham** [comment]
Could you please share more about how you are doing the build? Preferably in a PR where we could more easily discuss changes

**Comment by njzjz** [comment]
> Could you please share more about how you are doing the build? Preferably in a PR where we could more easily discuss changes

#224

**Comment by jakirkham** [comment]
Thanks Jinzhe! 🙏

Will keep an eye on that PR
