### ISSUE TITLE
Pytorch 2.0

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pytorch-cpu-feedstock#151]
Pytorch 2.0 recently got [announced](https://pytorch.org/get-started/pytorch-2.0/), and it looks like it'll bring lots of goodies.

However, with the strong focus on the new compiler backend, things are predictably getting heavier for the build. Seems the default backend will be triton, which we have in conda-forge [already](https://github.com/conda-forge/triton-feedstock), but so far only for linux-x64 + CUDA (no CPU version). That feedstock is also pushing hard against the 6h limit.

Release is planned March 2023.

If we have the capacity, I think it'd make sense to start playing with this, perhaps even pushing into a dev branch, so that we might have a chance to provide feedback on critical issues before release.

**Comment by hmaarrfk** [comment]
We should likely create a branch for 1.13 and migrate it. While publishing rc to a dev channel. We can do this, even if just for the CPU builds.

**Comment by h-vetinari** [comment]
IMO 1.13 can stay on main for a while, we only need a dev branch and `pytorch_dev` label. OTOH I think we could already start before the rc phase

**Comment by hmaarrfk** [comment]
We could make a release candidate branch branch and release to a non main channel if you want

**Comment by h-vetinari** [comment]
We can start with a PR; if we have the resources to create builds and push them to a dev channel, all the better

**Comment by h-vetinari** [comment]
https://github.com/pytorch/pytorch/releases/tag/v2.0.0 was released today! :)

**Comment by Tobias-Fischer** [comment]
Hi all,
Happy to help out if you need a hand. @hmaarrfk: You have quite a few draft/WIP PRs. Will it make sense to get some merged first, as this would simplify the version update? Or is it best to base a v2 branch on top of main?

**Comment by hmaarrfk** [comment]
I've mostly given up on my experimental PRs.  main is the best to follow.

**Comment by Tobias-Fischer** [comment]
Just letting you know that I’ve been working on this and I’m pretty close, at least for the non-cuda Linux-64 build. Will create a PR next week

**Comment by h-vetinari** [comment]
Closed by https://github.com/conda-forge/pytorch-cpu-feedstock/pull/165

**Comment by h-vetinari** [comment]
Triton discussion continues in https://github.com/conda-forge/pytorch-cpu-feedstock/issues/166
