### ISSUE TITLE
Do we really need to run-depend on ninja?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pytorch-cpu-feedstock#161]
ninja as a run-dep was added in https://github.com/conda-forge/pytorch-cpu-feedstock/commit/d1b3b1f04369c59e50fd0cd7d491f5ef7ca3c64e by @isuruf.

The comment says "Need ninja to load C++ extensions", but shouldn't that be on the consuming feedstock to have ninja available, or is this necessary even just to use pytorch?

I ask because having ninja present in the host-env in https://github.com/conda-forge/torchtext-feedstock/pull/7 picks up the wrong ninja during cross-compilation (not the one from the build env with the right CPU type), and it seems a bit gratuitous to me to run-depend on a build tool like that.

**Comment by hmaarrfk** [comment]
![image](https://user-images.githubusercontent.com/90008/216210979-8d0d54c4-0bed-416b-ba19-80ffa58f4380.png)
from the https://anaconda.org/pytorch/pytorch/files

it seems we do not.

I also tried to search for mentions of ninja in the python pytorch code. i couldn't find anything that was relevant.

**Comment by hmaarrfk** [comment]
it might be we no longer even need numpy.

**Comment by rgommers** [comment]
> The comment says "Need ninja to load C++ extensions", but shouldn't that be on the consuming feedstock to have ninja available, or is this necessary even just to use pytorch?

I assume that that relates to https://pytorch.org/docs/stable/cpp_extension.html. That's something you can use at runtime - but it's fairly niche/advanced functionality, so having a non-optional `ninja` runtime dependency does not seem needed for that.

**Comment by h-vetinari** [comment]
> Given the recent troubles with OSX compilation, maybe you can write a repodata patch removing the dependency?

Created https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/397. I only applied it to the last version to not wake sleeping dogs (so to speak), but if desired it'd be easy to extend the range where we do this.
