### ISSUE TITLE
PyTorch: Support CUDA 12

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pytorch-cpu-feedstock#163]
Depends on issue ( https://github.com/conda-forge/staged-recipes/issues/21382 )

**Comment by jakirkham** [comment]
Here's upstream's CUDA 12 tracking issue ( https://github.com/pytorch/pytorch/issues/91122 )

Note: This depends on the release of PyTorch 2.1.0

**Comment by weiji14** [comment]
[PyTorch 2.1](https://pytorch.org/blog/pytorch-2-1) is released - https://github.com/pytorch/pytorch/releases/tag/v2.1.0. Should support CUDA 12.1 - https://github.com/pytorch/pytorch/pull/107295

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/pytorch-cpu-feedstock/pull/195 )

Also 2.1.0 is handled in PR ( https://github.com/conda-forge/pytorch-cpu-feedstock/pull/199 )
