### ISSUE TITLE
Enable other BLAS implementations with CUDA

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pytorch-cpu-feedstock#177]
Recently there was some work in PR ( https://github.com/conda-forge/pytorch-cpu-feedstock/pull/175 ) to enable different BLAS implementations to be used with PyTorch in the CPU-only case. Am curious if this can be extended to the CUDA case

Has this been explored before? If so, would be interested to learn what those past attempts learned. If not, would be curious to know if there are issues that would need to be addressed first

**Comment by mgorny** [comment]
Unless I'm mistaken, it's technically possible to use CUDA + generic BLAS. I've just tried and it builds just fine (just had to remove the respective skips).

That said, I think the main problem is that allowing a second BLAS implementation would double the number of variants. And the CUDA variants are both very slow to build and are quite big. I think that the first problem can be somewhat circumvented using ccache (at least during my testing I didn't notice the second build rebuilding CUDA objects again).

If @hmaarrfk is okay with these, I can make a PR to stop skipping them; either for all CUDA variants or a subset of them.

**Comment by hmaarrfk** [comment]
I would likely just drop 11.8 if it were up to me. 

Ubuntu all the way back to 20.04 enables installation of cuda 12. 

If you want to try to add caching that is fine too, but historically it has been more pain than not.

The second blas variant has been a long requested feature so I'm all in!

**Comment by mgorny** [comment]
> I would likely just drop 11.8 if it were up to me.

Ok, I'll put up a PR with that + enabling generic BLAS (tomorrow, I think), and let's see what others think.

> If you want to try to add caching that is fine too, but historically it has been more pain than not.

Well, I've only succeeded while using it locally while calling `conda build` directly. I honestly have no clue how to do it with Docker — probably will need wider ecosystem changes.

**Comment by jakirkham** [comment]
What are the MKL bits used here for?

If it is just MKL-DNN, perhaps that makes less sense in the CUDA builds, in which case we could simply switch to generic BLAS in that case. That would avoid an additional build job.

Alternatively if it is straightforward to identify and pull in the MKL bits that are needed outside of BLAS and LAPACK, it may be possible to always use a generic BLAS and pull in a more focused portion of MKL

**Comment by hmaarrfk** [comment]
There were apparently some uses of FFT routines.

**Comment by mgorny** [comment]
> What are the MKL bits used here for?

Well, I don't know exactly but the code has a fair number of `#if AT_MKL_ENABLED()` conditions. Aside from FFT mentioned above (where it's used alternately to PocketFFT), they seem to also control some optimized code paths for MKL vs. other BLAS implementations.

**Comment by rgommers** [comment]
`mkl-fft` usage is probably less relevant nowadays. It predates the use of PocketFFT in PyTorch. Back then there was a hard dependency on MKL for that, but I'm not even sure that `mkl-fft` is any faster than PocketFFT.

BLAS/LAPACK performance is much more relevant today I think. The argument from PyTorch devs always was that performance of PyTorch is critical to them, and they don't want to give their users a suboptimal choice, nor receive performance-related bug reports. That said, if the test suite passes with alternate BLAS implementations, it's reasonable for Conda-forge to offer that choice I think. It can make it easier to install PyTorch in a larger environment with other packages that have their own BLAS/LAPACK dependencies.

**Comment by isuruf** [comment]
I forgot to comment here. Is there an actual user need to have other BLAS implementations with CUDA? Note that there are other BLAS implementations without CUDA.

**Comment by hmaarrfk** [comment]
I sometimes get environments where `nomkl` gets installed for one reason or an other. It in those, seeing pytorch downgrade all the way to the CPU version is really troublesome.

So I would be one such user.

Perhaps we can bump MKL above the non-mkl with a build number?
