### ISSUE TITLE
Bump pytorch version to 2.0.1

### ISSUE THREAD

**Issue by jkleckner** [conda-forge/pytorch-cpu-feedstock#178]
### Comment:

Pytorch 2.0.1 appears to be primarily bugfixes:

https://github.com/pytorch/pytorch/releases/tag/v2.0.1

**Comment by jakirkham** [comment]
It's being worked on ( https://github.com/conda-forge/pytorch-cpu-feedstock/pull/176 )

**Comment by hmaarrfk** [comment]
Generally we try to stay up to date.

I would like to close this to avoid unnecessary "Issue noise" but do feel free to help by making a PR and tacking one of the architectures.
