### ISSUE TITLE
Mega builds instead of tiny builds

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pytorch-cpu-feedstock#202]
### Comment:

In https://github.com/conda-forge/pytorch-cpu-feedstock/issues/108 a proposal was made to split up the package into tiny chunks.

One challenge I faced is that this really goes against upstream's versionning practices for certain things like XNNPACK. 

The alternative I see is to actually go the other way, and to go for "megabuilds".

1. Build libtorch in a split package.
2. Do not delete the output files
3. Build the different python versions

This will tip us over the edge on the 6 hour, but we are already there. The current problem is rebuilding the CUDA stuff, is done 5 times, for python 3.8 through 3.12..... not fun....

just an idea I wanted to throw out there in case somebody had time to try it out.

**Comment by RaulPPelaez** [comment]
I belive this broke some of my feedstocks that depend on torch. I started getting this error on new releases:
```shell
["  ERROR (torchmd-net,lib/python3.11/site-packages/torchmdnet/extensions/torchmdnet_extensions.so): .. but ['conda-forge/linux-64::libtorch==2.1.0=cuda120_h86db2e7_302'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  ERROR (torchmd-net,lib/python3.11/site-packages/torchmdnet/extensions/torchmdnet_extensions.so): .. but ['conda-forge/linux-64::libtorch==2.1.0=cuda120_h86db2e7_302'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  ERROR (torchmd-net,lib/python3.11/site-packages/torchmdnet/extensions/torchmdnet_extensions.so): .. but ['conda-forge/linux-64::libtorch==2.1.0=cuda120_h86db2e7_302'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)"]
```
https://github.com/conda-forge/torchmd-net-feedstock/pull/11

Stumbled on to this when I read about the previously non-existent libtorch package. I had to add libtorch as a dependency.

**Comment by njzjz** [comment]
I tried to migrate from pytorch to libtorch at https://github.com/conda-forge/abacus-feedstock/pull/25, since it's a C++-only project. Everything was good, but I had to manually pin libtorch, since there is no global pin.

**Comment by hmaarrfk** [comment]
xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5412
