### ISSUE TITLE
Do we use track_features in the correct output?

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/pytorch-cpu-feedstock#211]
### Comment:

We use `track_features` to down-weigh CPU builds. However, it is currently being used in the `pytorch-cpu` output rather than the `pytorch` output:

https://github.com/conda-forge/pytorch-cpu-feedstock/blob/7c7a57b7515eaeda67d3879b56b68466f38f0b0d/recipe/meta.yaml#L198-L207

In my opinion, we should use it for the `pytorch` output instead - as this is the output which can generate both CPU and CUDA builds and we want to down-weigh the CPU build there. Using it in the `pytorch-cpu` output does not make sense, does it? As the user specifies they want the cpu build in this case explicitly.

I've observed a few times that `mamba install pytorch` installs the CPU build, and I never knew why - this might be the reason.

**Comment by hmaarrfk** [comment]
We decided to use build numbers to prioritize the GPU instead:
https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/recipe/meta.yaml#L8

it may be some cuda incompatibility between other preinstalled cuda tools too.

This has been the typical source of CPU being preferred for me.

**Comment by Tobias-Fischer** [comment]
Ah I see. All good then :)
