### ISSUE TITLE
Need a migration to pytorch 2.1.2?

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/pytorch-cpu-feedstock#222]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In https://github.com/conda-forge/pytorch3d-feedstock/pull/6 we get issues resolving the environment.

It can be condensed down to `CONDA_SUBDIR=osx-64 micromamba create -n test1 torchvision=0.16 python=3.10 pytorch=2.1.2` which fails, but `CONDA_SUBDIR=osx-64 micromamba create -n test2 torchvision=0.16 python=3.10 pytorch=2.1` which succeeds.

I think we need to migrate all downstream packages to pytorch 2.1.2 to resolve this, as somehow 2.1.0 and 2.1.2 are incompatible. Or, do we need a migrator to libtorch instead of relying on pytorch?

Note, problem occurs on linux-64 as well.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by hmaarrfk** [comment]
why is libcublas-dev pinned to >=12.3???? we typically try to build for 12.0.

**Comment by Tobias-Fischer** [comment]
Where is that @hmaarrfk?

**Comment by hmaarrfk** [comment]
![image](https://github.com/conda-forge/pytorch-cpu-feedstock/assets/90008/e5768b57-17a9-4a19-99c5-5e4675ced3a9)

in the build: 

linux linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.22python3.10.____cpython

**Comment by Tobias-Fischer** [comment]
I’m not sure where this comes from - there’s nothing in the meta.yaml. But the problem occurs even in CPU builds, e.g. on osx

**Comment by hmaarrfk** [comment]
Right. I noticed that as well after you asked

**Comment by jakirkham** [comment]
Good observation Mark

Tobias, I think we want to make this change to that PR: https://github.com/conda-forge/pytorch3d-feedstock/pull/6#issuecomment-1962268341

**Comment by Tobias-Fischer** [comment]
My best guess is that this line causes a pin to the patch version, as opposed to the minor version that is pinned globally: https://github.com/conda-forge/pytorch-cpu-feedstock/blob/201dc57fed23c4b9bf475d65b3fc145a333f522b/recipe/meta.yaml#L267

Which in turn makes pytorch 2.1.0 and 2.1.2 incompatible - so if one dependency A was built with one patch version it is incompatible with dependency B that was built with another patch version.

**Comment by hmaarrfk** [comment]
why do you think that makes them incompatible? libtorch 2.1.2 should be installed with pytorch 2.1.2. No other version.



I think it may be related to https://github.com/conda-forge/conda-smithy/issues/1847#issuecomment-1962395361

Can you maybe create a reproducer of an environment that can't be solved with

```
CONDA_OVERRIDE_CUDA=12.0 mamba create --name t pytorch=2.1 ....
```

that would really help narrow it down.

**Comment by Tobias-Fischer** [comment]
Isn’t that what I provided in my first comment here? https://github.com/conda-forge/pytorch-cpu-feedstock/issues/222#issue-2152063594

Also, I think it nothing to do with cuda as it happens on osx as well.

**Comment by hmaarrfk** [comment]
Oh sorry. Missed that

**Comment by hmaarrfk** [comment]
![image](https://github.com/conda-forge/pytorch-cpu-feedstock/assets/90008/c2b0d4fa-4940-49ab-b0e7-d01134b328f6)


maybe `2.1` and `2.1.*` are not the same in the pinning file? that could be the issue with the torchvision recipe

https://github.com/conda-forge/torchvision-feedstock/blob/main/recipe/meta.yaml#L8

**Comment by Tobias-Fischer** [comment]
All good for now, thanks to https://github.com/conda-forge/torchvision-feedstock/pull/89

**Comment by hmaarrfk** [comment]
i'm really not sure what fixed it tbh, 

rebuilding torchvision effectively "mirated" to pytorch  2.1.2 so maybe you are right.....

**Comment by Tobias-Fischer** [comment]
I still believe that this is true: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/222#issuecomment-1962315196

**Comment by hmaarrfk** [comment]
Got it. So the .* helped
