### ISSUE TITLE
pip check says: torch 1.6.0 requires future, which is not installed

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/pytorch-cpu-feedstock#24]
From this build:
- https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=251942&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=782

Given the pain of getting this build, I'll just be adding it downstream for the time being, but would be nice to fix at _some_ point... perhaps as part of getting #23 up?

**Comment by hmaarrfk** [comment]
Can you help us create a reproducing issue:

```
(dev) ✘-INT ~/git [master|⚑ 4] 
22:50 $ pip list | grep future
(dev) ✘-INT ~/git [master|⚑ 4] 
22:51 $ pip list | grep torch
torch                         1.6.0
(dev) ✔ ~/git [master|⚑ 4] 
22:51 $ conda list | grep torch
pytorch-cpu               1.6.0           cpu_py38h3369884_0    conda-forge
(dev) ✔ ~/git [master|⚑ 4] 
22:51 $ python 
Python 3.8.6 | packaged by conda-forge | (default, Nov  2 2020, 13:59:27) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> # see no warning.....

```
FYI, i wouldn't depend on this package just yet. We are working to create a unified `pytorch` package. 

Installing this pytorch-cpu and `pytorch::pytorch` package could conflict...

**Comment by hmaarrfk** [comment]
oh this is pip check.

i'm not sure this is the best test. but ok.

**Comment by hmaarrfk** [comment]
shoudl be fixed in https://github.com/conda-forge/pytorch-cpu-feedstock/pull/23


Let me know if you will still have issues at the end of the week (this packag takes a while to build)

**Comment by bollwyvl** [comment]
> i'm not sure this is the best test. but ok.

Yes, just pip check. It's not great, but it's the best we have, i guess. I'd really love something more reliable, but so it goes. In the meantime, I've added `future` over on`tpot`, and will report back if i run into issues.

> shoudl be fixed in #23

:tada: Thank you

> Let me know if you will still have issues at the end of the week (this package takes a while to build)

Definitely out of my area of expertise: super thankful for the work, of course! Will let you know!

**Comment by bollwyvl** [comment]
> Installing this pytorch-cpu and pytorch::pytorch package could conflict...

On this you raise a good point: likely for the particular downstream, tpot, which _just_ added torch as a hard dependency, we need to go to multiple outputs, and have an option, e.g. `tpot-no-torch` that doesn't include this one. I kinda wish there was a convention for advertising these kinds of wrinkles little more robustly...

**Comment by hmaarrfk** [comment]
i think we should have GPU support by the end of the week, in which case we will have a `pytorch` package.

**Comment by hmaarrfk** [comment]
i'm going to close this now that the new build should be out.

Let me know if you still have problems by reopening this.

**Comment by bollwyvl** [comment]
Thanks!
