### ISSUE TITLE
Linux aarch64 also complaining about no numpy support

### ISSUE THREAD

**Issue by erykoff** [conda-forge/pytorch-cpu-feedstock#258]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Following on with https://github.com/conda-forge/pytorch-cpu-feedstock/issues/251 the problem does not seem isolated to osx.  On linux aarch64 we have `PyTorch: RuntimeError: PyTorch was compiled without NumPy support`.  cc @hmaa

### Installed packages

```shell
This is in a CI but:
  - pytorch=2.4.0=cpu_generic_py311h0a0624f_0
```

### Environment info

```shell
I don't have access to this.
```

**Comment by jakirkham** [comment]
Duplicate of issue: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/254

**Comment by jakirkham** [comment]
Continued in issue: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/266

**Comment by hmaarrfk** [comment]
hmm sorry for not continuing this one....
