### ISSUE TITLE
Mitigate performance degradation on linux-aarch64 CUDA builds by incorporating the linker script from upstream

### ISSUE THREAD

**Issue by leofang** [conda-forge/pytorch-cpu-feedstock#264]
xref: https://github.com/pytorch/pytorch/pull/121975

An internal NVIDIA report pointed out a performance issue when working with conda-forge PyTorch + OpenMM. The issue can be mitigated by using the linker script from the above upstream PR. We should have a build step that sets `USE_PRIORITIZED_TEXT_FOR_LD=1` for linux-aarch64 + CUDA 12+. A further, optional step that we can take is to regenerate `cmake/prioritized_text.txt` at build time.

**Comment by hmaarrfk** [comment]
Yeah. I’ve been seeing the warning and wondering what it meant. 

I’ve been meaning to look into it. But the aarcc stuff seems to be failing for other reasons.

**Comment by jakirkham** [comment]
AFAICT that fix went in commit ( https://github.com/pytorch/pytorch/commit/a6080f79e9ea895cf45578e9fcc03e7423257a65 ), which was included in 2.4.0:

<img width="1840" alt="Screenshot 2024-10-01 at 4 04 27 PM" src="https://github.com/user-attachments/assets/fffa6f76-24da-4e71-9570-d1badb8c8ff3">

So simply shipping 2.4.0 should be sufficient to fix the issue

**Comment by leofang** [comment]
@jakirkham This feature is opt-in not opt-out. The linker script support is included in the upstream, yes, but the default value of `USE_PRIORITIZED_TEXT_FOR_LD` is set to 0:
https://github.com/pytorch/pytorch/blob/876580454272d3893ddcbb923717edaa1986630f/setup.py#L1156
and it needs to be set to 1 at build time, if building from source.

**Comment by jakirkham** [comment]
Sorry for misunderstanding. Thank you for clarifying! 🙏

**Comment by hmaarrfk** [comment]
(thank you for continuing the discussion here)
