### ISSUE TITLE
Python 2.4.0 + aarch compiled without numpy support

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pytorch-cpu-feedstock#266]
~Possibly relevant:~ We encountered a "PyTorch was compiled without NumPy support" error when running on Linux aarch64 + CUDA (on NVIDIA GH200) using the conda-forge build of PyTorch 2.4.0.

Relevant output from `conda list` for the environment in which the error was encountered:

```text
pytorch                   2.4.0           cuda120_py312haadfe8f_200    conda-forge
pytorch-gpu               2.4.0           cuda120py312hecaec72_200    conda-forge
```

Rolling back to 2.3.0 remedied this issue. Looking at the build number, it seems that the build we installed preceded merging PR #252.

_Originally posted by @jcwomack in https://github.com/conda-forge/pytorch-cpu-feedstock/issues/254#issuecomment-2319090902_

**Comment by jcwomack** [comment]
Thanks for your work on in the @hmaarrfk! Greatly appreciated.

**Comment by jakirkham** [comment]
cc @erykoff @HMAA

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender
