### ISSUE TITLE
Using ccache and consolidating builds?

### ISSUE THREAD

**Issue by mgorny** [conda-forge/pytorch-cpu-feedstock#295]
### Comment:

Looking at the builds for my last pull request: https://github.com/conda-forge/pytorch-cpu-feedstock/actions/runs/12059424434/job/33628141944

- generic CPU build takes around 3h
- a CUDA build takes between 7h and 10h

All things considered, I'm pretty sure there's at least some, if not significant duplication there. I think we could spend less energy (though at the cost of losing parallelization — so not necessarily time) by building things sequentially, as subpackages, and using ccache.

Given that CPU and CUDA builds use different compiler versions, we could at least try splitting them into:

- a sequential generic-then-MKL CPU build
- a sequential generic-then-MKL GPU build

I'm not sure but I think the latter may actually save a lot of time, provided that CUDA objects matched from ccache.

**Comment by isuruf** [comment]
I don't think it makes sense to do this. CI time is cheap, whereas developer time hunting bugs related to complicating the builds is expensive.

**Comment by mgorny** [comment]
Yeah, I guess you're right. On top of that, I've missed that we can't trivially have outputs with the same package name.
