### ISSUE TITLE
Add license informaton about vendored packages

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pytorch-cpu-feedstock#34]
In https://github.com/conda-forge/pytorch-cpu-feedstock/issues/7#issuecomment-745524671 @seemethere had offered to help with some packaging work for conda-forge.

@isuruf suggested that we work on https://github.com/conda-forge/pytorch-cpu-feedstock/issues/7#issuecomment-745550433

> @seemethere, thanks for the offer. One task you could help with is a way to collect the licenses/copyright notices of the third party dependencies to comply with their license terms.

I'm creating this issue so we can close the original GPU issue.

**Comment by rgommers** [comment]
Typically there's a `LICENSE` or `LICENSE.TXT` or `COPYING` file in each subdirectory under `third_party`. It would be useful to specify what's actually needed here (format of metadata) - maybe link to a good example for another package?

**Comment by jaimergp** [comment]
This is [what we did for OpenMM.](https://github.com/conda-forge/openmm-feedstock/blob/master/recipe/meta.yaml#L116-L121)

**Comment by isuruf** [comment]
What we need is a way to get a single license file that concatenates all of the license files.

**Comment by rgommers** [comment]
> What we need is a way to get a single license file that concatenates all of the license files.

That should normally be present in an sdist or wheel too - I'd consider it a bug if that's missing. Wheels don't contain the correct info, and sdists aren't present at all on PyPI (different issue and probably on purpose, but also questionable - I'll file some issues).

**Comment by isuruf** [comment]
> That should normally be present in an sdist or wheel too 

It's not available and not available in the conda packages that pytorch distributes either. The only copyright notices found are those of `pytorch` sources and `caffe2` sources and completely ignore the copyright notices of dozens of third party modules used.

**Comment by rgommers** [comment]
This is now available: https://github.com/pytorch/pytorch/blob/master/third_party/LICENSES_BUNDLED.txt. That file is included in the pytorch 1.8.0 wheels as well.
