### ISSUE TITLE
Archive repo and move to pytorch-feedstock

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pytorch-cpu-feedstock#36]
@isuruf is it wise to move this repo or should I PR to staged-recipes to create a fully new pytorch-feedstock?

**Comment by jamestwebber** [comment]
poking my head in here because I was going to submit a PR for 1.8...is this repo becoming obsolete/getting moved?

**Comment by isuruf** [comment]
@jamestwebber, that's fine. Send a PR here and we can transfer if we move.

**Comment by jamestwebber** [comment]
Well, I will try! It looks like updating the version might get pretty hairy, if there is any guidance that'd be great.

**Comment by hmaarrfk** [comment]
Given this recipe's difficulty, I'm going to close this issue.

Users can find this feedstock through https://conda-forge.org/feedstock-outputs/
