### ISSUE TITLE
`module 'torch.distributed' has no attribute 'init_process_group'`

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pytorch-cpu-feedstock#46]
While trying to build https://github.com/conda-forge/allennlp-feedstock/pull/19, there were first issues à la:
```
from torch.distributed import ReduceOp
ImportError: cannot import name 'ReduceOp'
```

This seems to have been fixed in the most recent builds, but the allennlp test suite still fails with
```
module 'torch.distributed' has no attribute 'init_process_group'
```

The upstream AllenNLP devs say that things work with the builds from the pytorch channel.

**Comment by dirkgr** [comment]
I am the upstream allennlp dev. I can confirm that this works with the pytorch channel builds.

**Comment by isuruf** [comment]
That's expected given the default value. See https://github.com/pytorch/pytorch/blob/c3745dc5808aae7f3a6135de5e773286c46e4837/torch/distributed/__init__.py#L10-L15

**Comment by dirkgr** [comment]
Can the setting be changed for this build of pytorch?

**Comment by h-vetinari** [comment]
It seems the pytorch channel builds with `USE_DISTRIBUTED=1` on MacOS then? Would be good to have this for the conda-forge builds as well.

**Comment by rgommers** [comment]
> It seems the pytorch channel builds with `USE_DISTRIBUTED=1` on MacOS then?

Indeed. Explanation for why it's not default in the repo on macOS: https://github.com/pytorch/builder/blob/master/conda/build_pytorch.sh#L133

**Comment by h-vetinari** [comment]
> Indeed. Explanation for why it's not default in the repo on macOS: https://github.com/pytorch/builder/blob/master/conda/build_pytorch.sh#L133

Thanks. Since [`libuv`](https://github.com/conda-forge/libuv-feedstock) is available in conda-forge, there shouldn't be a fundamental roadblock to do the same in conda-forge?
