### ISSUE TITLE
Packge naming discussion

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pytorch-cpu-feedstock#6]
Issue:

The package from the pytorch channel doesn't have a `-gpu` specifier.

Currently the naming convention stands as

DNE: Does not exist

|package name  |linux  | MacOSX | Windows |
|--------------|-------|--------|---------|
| pytorch::pytorch      | GPU  | CPU    | GPU    |
| pytorch::pytorch-cpu  | CPU   | DNE    | CPU     |
| pytorch::pytorch-gpu  | DNE   | DNE    | DNE     |
| conda-forge::pytorch-cpu | CPU | CPU | CPU |
| conda-forge::pytorch-gpu | GPU | GPU??? | GPU |
| conda-forge::pytorch | Depends | Depends | Depends |

Since the GPU packages do not exist yet on conda-forge, this means that if a user installs:

This means that if somebody installs:
```
conda install pytorch
```
they will get vastly different performance if the solver converged on the solution from the pytorch channel and from the conda-forge channel.

I think (but I'm also biased) the the naming convention that I am proposing for the conda-forge packages is probaly correct. We can work on getting the meta package and packge selection working with the current version. I guess I'll work on creating the meta package and `-cpu` selector once `v1.1.0` gets built.

**Comment by hmaarrfk** [comment]
the challenge becomes if a conda-forge package decides to depend on `pytorch-gpu` from conda-forge, but then the user tries to download the packages from the `pytorch` channel. They would not be able to install things.

**Comment by jakirkham** [comment]
I've been playing with a way to handle this using variants. Will try to point you to an example after SciPy. Please ping me (nicely) if I forget. 🙂

**Comment by hmaarrfk** [comment]
for the me the main challenge will be actually building it with GPU support. That seems non trivial! Will love to see what you can do!

**Comment by jakirkham** [comment]
Please see [this comment]( https://github.com/conda-forge/pytorch-cpu-feedstock/issues/7#issuecomment-510324568 ) for current/planned work. Happy also to work with others interested in helping move this forward. 😉

**Comment by benjaminrwilson** [comment]
@hmaarrfk -- was there ever a conclusion for how handle this?

**Comment by hmaarrfk** [comment]
it's just a pretty minor thing, that always seems lower priority compared to keeping up with other build challenges for pytorch and the rest of the ecosystem.

honestly, it's confusing, but we need to focus our efforts on getting builds for windows to converge. that seems like it would be more helpful for others

**Comment by hmaarrfk** [comment]
This is now out of date.

The new conversation has moved to: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/74
