### ISSUE TITLE
Use more system libraries

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pytorch-cpu-feedstock#60]
I get that this comes at a cost, I just wanted to list these out in case they can help us get down to a below 6 hour build time:

I found these variables in the `cmake/Depenencies.cmake`
* `USE_SYSTEM_PTHREADPOOL`
* `USE_SYSTEM_CPUINFO`
* `USE_SYSTEM_XNNPACK`
* `USE_SYSTEM_FP16`
* `USE_SYSTEM_EIGEN_INSTALL`
* `USE_SYSTEM_BIND11`
* `USE_SYSTEM_NCCL`
* `USE_SYSTEM_GLOO`
* `USE_SYSTEM_ONNX`

For some, it might be useful to decouple them (NCCL) for others maybe not.

**Comment by isuruf** [comment]
`USE_SYSTEM_XNNPACK` seems to be the most beneficial.

**Comment by hmaarrfk** [comment]
do we have xnnpack feedstock? do you think it is safe to use it since it is "undocumented" in their setup.py file?

**Comment by isuruf** [comment]
It's documented at https://github.com/pytorch/pytorch/blob/e318058ffe662d426617a405fb21e6470dfc1219/CMakeLists.txt#L369, so I think it's fine to use.

No, we don't have a xnnpack feedstock, but it shouldn't be too hard.

**Comment by hmaarrfk** [comment]
unfortunately, xnnpack doesn't have any versions. at least none that i can find glancing at the Google GitHub page for it.

seems like we would be creating version numbers. which I'm not a fan of.

**Comment by isuruf** [comment]
We can go for a date based version numbering. It's not ideal, but better than building pytorch manually.

**Comment by isuruf** [comment]
Debian has versions like `0.0~git20201221.e1ffe15`. We can go with something like  `0.0.2020.12.21.e1ffe15`

**Comment by hmaarrfk** [comment]
would we create sacred versions for the ones pytorch pins to?

**Comment by isuruf** [comment]
Yes, we should create versions needed by pytorch. For eg: pytorch 1.9.0 uses 55d53a4e7079d38e90acd75dd9e4f9e781d2da35,
so `0.0.0.2021.02.23.55d53a4` and have `run_exports` that pin exactly.

**Comment by isuruf** [comment]
Nvm, xnnpack will save only a few minutes.

**Comment by hmaarrfk** [comment]
Ok thanks.

NCCL seems to take 20-30 mins to build. That might just throw us under the 6 hours. Lets see.

The other option I want to try first is to use mamba but after NCCL results.

**Comment by hmaarrfk** [comment]
As expected, XNNPACK is quick to compile
https://github.com/conda-forge/staged-recipes/pull/15865

**Comment by andfoy** [comment]
@hmaarrfk @isuruf @IvanYashchuk, I'm going to help with reducing the building time of PyTorch on the conda-forge CIs, could you please let me know which strategies have been already tried, even unsuccessful?

**Comment by rgommers** [comment]
This issue hasn't seen activity in 3 years and I think is superseded by gh-108. Can this be closed?
