### ISSUE TITLE
Remove defunct dependencies

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pytorch-cpu-feedstock#80]
It seems that some dependencies got removed from the `torch` pacakge on pypi
![image](https://user-images.githubusercontent.com/90008/148230298-5e7fd8bc-6935-4b4e-b0b7-4d44b6bd54c7.png)

It only requires typing extensions, but not setuptools or future. It is pretty hard for me to audit the code to ensure that this is true but if somebody else can confirm that would be great.

**Comment by rgommers** [comment]
`setuptools` is only a build-time dependency. `future` is a Caffe2 dependency, but not needed for `torch`. So only requiring `typing_extensions` is right.

**Comment by hmaarrfk** [comment]
Thank you for confirming.

**Comment by hmaarrfk** [comment]
Personally, i have 11/16 builds done for https://github.com/conda-forge/pytorch-cpu-feedstock/pull/77

This cleanup is going to have to wait for the next release in my mind.

**Comment by h-vetinari** [comment]
> `setuptools` is only a build-time dependency

That's not quite right. Unfortunately, pytorch has an undeclared runtime dependence on setuptools (until 1.11.0, see pytorch/pytorch#71280), and worse, ends up breaking with newer setuptools. I saw this in the test suite of a package depending on pytorch ([CI](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=454944&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642)),, so I had to add something like:
```
        # until v1.11.0, pytorch has an undeclared dependency on setuptools,
        # see pytorch/pytorch#71280, and breaks with new versions
        - setuptools <59.5
```

Note that `setuptools <60` still ran into the same error, but I haven't figured out which version broke it, and just went back to the last version that had passed in CI.

<details>
<summary>Error with newer setuptools</summary>

```
  File "[...]/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'setuptools._distutils' has no attribute 'version'
```

</details>

**Comment by h-vetinari** [comment]
I'm wondering if we should add some repodata patches, because all it takes is _any_ other package in the environment pulling in a newish setuptools for current pytorch builds to break.

CC @conda-forge/pytorch-cpu @isuruf

**Comment by rgommers** [comment]
I'll follow up on the PyTorch side - having this undeclared runtime dependency is a bad idea. It's made lazy in pytorch 1.11.0, but it still exists if you try to use `__version__`.

> I'm wondering if we should add some repodata patches, because all it takes is _any_ other package in the environment pulling in a newish setuptools for current pytorch builds to break.

Probably a good idea.

**Comment by hmaarrfk** [comment]
yes. I would be fine with this. please make the PR to the pinnings repo

I'm going to rebuild it with the constraint in:
https://github.com/conda-forge/pytorch-cpu-feedstock/pull/89/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9a

Can you confirm that it is `<59.6` or `<59.5` ? How do I trigger the failure? I could add it as a test

**Comment by hmaarrfk** [comment]
@rgommers i would like to unpin the upper limit setuptools. Do you think it is enough to add the test
```
python -c "import torch; print(torch.__version__)"
```
to ensure that the correct version of setuptools is installed?

**Comment by rgommers** [comment]
yes that should be enough. unpinning should be fine now

**Comment by hmaarrfk** [comment]
now as in 1.11 or 1.10.1?

**Comment by rgommers** [comment]
`1.11.0` I believe.
