### ISSUE TITLE
which blas

### ISSUE THREAD

**Issue by ngam** [conda-forge/pytorch-cpu-feedstock#85]
I'm going to refer to the comment made https://github.com/conda-forge/pytorch-cpu-feedstock/pull/83#issuecomment-1019595569

I would suggest, that for this kind of optimization, that you demonstrate some real gains to be had by moving to accelerate. Maybe you can provide a benchmark showing the improvement? It is pretty easy to build things yourself and upload them to your channel. I strongly suggest that instead of waiting too long on the community for your own work anyway.

once we've established the gains, we can work on integrating it here

_Originally posted by @hmaarrfk in https://github.com/conda-forge/pytorch-cpu-feedstock/issues/84#issuecomment-1019997679_

**Comment by ngam** [comment]
https://pythonawesome.com/benchmarking-openblas-on-the-apple-m1/

**Comment by hmaarrfk** [comment]
Thank you for sharing. These are interesting. It is unclear to me what is "accelerate" in the benchmarks. Maybe you can elaborate on what they wrote. 

Finally, isuruf recommended:

> Please don't do this. Accelerate is a very experimental backend. Try instead to building with netlib variant which will give openblas by default and then users can use accelerate if they want to experiment.

**Comment by ngam** [comment]
Veclib is from Accelerate while vortex and zen are from OpenBLAS. However, this is besides the point for now --- we would need to show something about PyTorch in particular before moving forward. This is just additional info as I am trying to better understand this :) 

Again, my inspiration was from my work on mxnet where they _seemed_ to have a clear hierarchy. I would like to understand if that's just for packaging purposes (avoiding shipping yet another BLAS) or for actual performance reasons. One thing is really clear though: MKL is really the choice wherever possible, so you're making the perfect call here with forcing everything to use MKL (obviously MKL isn't available on osx-arm64 and that's the only narrow case we would be changing)

**Comment by ngam** [comment]
Just to expand on @isuruf's comment. I believe I understand where he comes from on two fronts:

1. There is the idea of replacing BLAS by the user like I showed in issue #82 (that's definitely experimental; he only added it recently; I will link the issue/discussion on that shortly)
2. The underlying issues with Accelerate itself some of which are documented in this comment:

**Comment by ngam** [comment]
Regarding the first point above, this will require a lot more work and may not be possible after all --- I think pytorch requires setting a BLAS clearly and maybe it would not work if you can just switch back and forth. Again, see #82. So our option would likely be to build with explicit CMAKE flag settings, I believe. 

Regarding the second point, that's an important and valid reason to avoid Accelerate altogether.

**Comment by hmaarrfk** [comment]
I'm not a blas expert, but compiling with netlib allows for the switch. If you compile with the underlying library straight, you cannot switch. Typically you need a bit of trickery.

For what its worth: pytorch has been open to PRs that allow customization like this.

**Comment by ngam** [comment]
> For what its worth: pytorch has been open to PRs that allow customization like this.

Good call, I will look around and open an issue upstream to ask about

**Comment by ngam** [comment]
closing this as we have two other issues addressing the same exact issue
